### ISSUE TITLE
Types for import API options missing batch_size

### ISSUE THREAD

**Issue by FLevent29** [typesense/typesense-js#115]
## Description

Type for import API options missing `batch_size`. As described [here](https://typesense.org/docs/0.22.2/api/documents.html#configure-batch-size) it is clearly an option and it does work (at the very least doesn't err) for me.

## Steps to reproduce

```typescript
// try to import some documents like so
const results = await this.typesenseClient
      .collections(this.collectionsName)
      .documents()
      .import(documents, { action: 'upsert', batch_size: 200 });
```

## Expected Behavior

I expect the code above to not err at transpilation time.

## Actual Behavior

I get `TS2769: No overload matches this call.   Overload 1 of 2, '(documents: string, options?: DocumentWriteParameters): Promise<string>', gave the following error.     Argument of type 'TypeSenseRecord[]' is not assignable to parameter of type 'string'.   Overload 2 of 2, '(documents: {}[], options?: DocumentWriteParameters): Promise<ImportResponse[]>', gave the following error.     Argument of type '{ action: "upsert"; batch_size: number; }' is not assignable to parameter of type 'DocumentWriteParameters'.       Object literal may only specify known properties, and 'batch_size' does not exist in type 'DocumentWriteParameters'.`.

## Metadata

**Typsense Version**: 0.22.2

**OS**: Windows 11 (10.0.22000.556)

**Comment by FLevent29** [comment]
It seems like messing with `batch_size` maybe is not such a good idea. I didn't increase it very much, and now I am getting a bunch of these
```
[Nest] 14720  - 03/23/2022, 4:57:23 PM    WARN [Typesense] Request #1648047443915: Request to Node 0 failed due to "undefined Request failed with HTTP code 503 | Server said: Not Ready or Lagging"
[Nest] 14720  - 03/23/2022, 4:57:23 PM    WARN [Typesense] Request #1648047443798: Request to Node 0 failed due to "undefined Request failed with HTTP code 503 | Server said: Not Ready or Lagging"
[Nest] 14720  - 03/23/2022, 4:57:23 PM    WARN [Typesense] Request #1648047443915: Sleeping for 0.1s and then retrying request...
[Nest] 14720  - 03/23/2022, 4:57:23 PM    WARN [Typesense] Request #1648047443798: Sleeping for 0.1s and then retrying request...
[Nest] 14720  - 03/23/2022, 4:57:23 PM    WARN [Typesense] Request #1648047443808: Request to Node 0 failed due to "undefined Request failed with HTTP code 503 | Server said: Not Ready or Lagging"
[Nest] 14720  - 03/23/2022, 4:57:23 PM    WARN [Typesense] Request #1648047443808: Sleeping for 0.1s and then retrying request...
```
and
```
[Nest] 14720  - 03/23/2022, 4:57:23 PM   ERROR [HarvestService] Error: Request failed with HTTP code 400 | Server said: Query string exceeds max allowed length of 4000. Use the /multi_search end-point for larger payloads.
Error: Request failed with HTTP code 400 | Server said: Query string exceeds max allowed length of 4000. Use the /multi_search end-point for larger payloads.
    at ApiCall.customErrorForResponse (C:\Users\delza\unitas-library\node_modules\typesense\src\Typesense\ApiCall.ts:323:15)
    at ApiCall.performRequest (C:\Users\delza\unitas-library\node_modules\typesense\src\Typesense\ApiCall.ts:195:38)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at TypesenseCoreService.upsertAndDeleteManyDocuments (C:\Users\delza\unitas-library\src\app\modules\typesense\typesense-core.service.ts:44:7)
    at C:\Users\delza\unitas-library\src\app\modules\harvest\worker\upsert-delete\upsert-delete-mrc-exp.ts:62:7
```
Some of my payloads once converted to JSONL are much larger than 4000 characters and they pass on fine, so the error must be coming from either this packages side or a bug in Typesense.

However if I leave `batch_size` alone, none of this happens.
