### ISSUE TITLE
Axios is not supported on Edge Runtime

### ISSUE THREAD

**Issue by viktorlarsson** [typesense/typesense-js#161]
## Description

As described in this ticket, Axios is not supported (and I don't think it will in any time near future) and you cannot use this library on an  Serverless edge functions for example like Vercel, AWS etc. (or any service worker like Cloudflare)

https://github.com/axios/axios/issues/5523

https://vercel.com/guides/library-sdk-compatible-with-vercel-edge-runtime-and-functions#library-recommendations

## Steps to reproduce

* Spin up a new NextJS app, create a new api endpoint using edge runtime. It will fail.

```
import typeSenseService from "@/services/typesense/typesense";
import type { NextRequest } from "next/server";
import { NextResponse } from "next/server";

export const config = {
  runtime: "edge",
};

export default async function handler(req: NextRequest) {
  if (req.method !== "POST") {
    return NextResponse.json({ error: "no" }, { status: 500 });
  }

  try {
    const { searchParams } = new URL(req?.url ?? "");
    const term = searchParams.get("term") as string;

    console.log(term);

   // Just a simple typesense search here
    const data = typeSenseService.search("index_name", term);

    return NextResponse.json({ result: data });
  } catch (e: any) {
    console.log(e);
    return NextResponse.json({ error: "no" }, { status: 500 });
  }
```

## Expected Behavior

* It should work if you move to fetch, or create more agnostic way to pass the httpClient. Example below:

```


export interface Fetch {
  (url: string, init?: RequestInit): Promise<Response>
}

export interface RequestInit {
  headers?: any
  method?: string
  body?: string
  redirect?: string
}

export interface Response {
  headers: Headers
  ok: boolean
  status: number
  statusText: string
  text: () => Promise<string>
  json: () => Promise<any>
}

export interface CallInfo extends RequestInit {
  name: string
  type: string
  url: string
  status: number
  statusText: string
  error?: Error
}

export interface FetcherOptions {
  record?: (info: CallInfo, data: string | Blob | ArrayBuffer | any) => Promise<void>
}

export interface Fetcher {
  (name: string, url: string, init?: RequestInit, childId?: string): Promise<Response>
}

export interface Recorder {
  (info: CallInfo, data: string | Blob | ArrayBuffer | any): Promise<void>
}

const record = async (
  name: string,
  url: string,
  init: RequestInit | undefined,
  type: string,
  options: FetcherOptions,
  response: Response,
  data: string | ArrayBuffer | Blob | any
): Promise<void> => {
  if (!options.record) {
    return
  }
  const info: CallInfo = {
    ...(init || {}),
    name,
    url,
    type,
    status: response.status,
    statusText: response.statusText
  }
  await options.record(info, data)
}

export default function wrap(fetch: Fetch, options: FetcherOptions = {}): Fetcher {
  return async (name: string, url: string, config: RequestInit = { headers: {} }): Promise<Response> => {
    const response = await fetch(url, config)

    const wrapMethod = (res: Response, methodName: string): void => {
      // @ts-ignore
      const original = res[methodName].bind(res)
      // @ts-ignore
      res[methodName] = async (...args) => {
        const result = await original(...args)
        await record(name, url, config, methodName, options, response, result)
        return result
      }
    }
    wrapMethod(response, 'json')
    wrapMethod(response, 'text')

    return response
  }
}


// Usage

const httpClient = wrap(axios, options)
const httpClient = wrap(fetch, options)

const ticketResponse = httpClient('unique-endpoint', '/api/tickets', {
  method: 'POST'
})
```
## Actual Behavior

it... should work :D

## Metadata

**Typesense Version**: 1.5.4

**OS**: Mac OS X

**Comment by denny64** [comment]
Any temporarily solutions to this?

**Comment by jasonbosco** [comment]
It would be a non-trivial amount of work to replace axios in typesense-js. 

So the workaround would be to use say `fetch` and call the Typesense HTTP APIs directly.

**Comment by leerobert** [comment]
It's worth exploring have an edge/deno supported js/ts library as many users are switching to such implementations for their backend. 

Related:
https://github.com/typesense/typesense-js/issues/95

**Comment by MickL** [comment]
That axios is not working on edge workers like Deno Deploy, Vercel Edge Functions or Cloudflare Workers is an absolute dealbreaker for me.

**Comment by leerobert** [comment]
> That axios is not working on edge workers like Deno Deploy, Vercel Edge Functions or Cloudflare Workers is an absolute dealbreaker for me.

You can just make `fetch('<urhost>/collection/`) calls but it is annoying. That's what we do though.

**Comment by miguelvictor** [comment]
Could we bump the version of axios to the latest one? I think the latest version of axios has the `fetch` adapter which should work for runtimes other than node.

**Comment by zwily** [comment]
I just tried this out on `typesense@2.0.0-0` (in a cloudflare worker) and get this error now:

```
[mf:err] TypeError: http_1.Agent is not a constructor
    at null.<anonymous> (/Users/zwily/Source/bhr/node_modules/.pnpm/typesense@2.0.0-0_@babel+runtime@7.23.2/node_modules/typesense/src/Typesense/ApiCall.ts:223:38)
    at step (/Users/zwily/Source/bhr/node_modules/.pnpm/tslib@2.6.2/node_modules/tslib/tslib.js:195:27)
    at Object.next (/Users/zwily/Source/bhr/node_modules/.pnpm/tslib@2.6.2/node_modules/tslib/tslib.js:176:57)
    at step (/Users/zwily/Source/bhr/node_modules/.pnpm/tslib@2.6.2/node_modules/tslib/tslib.js:180:143)
    at Object.next (/Users/zwily/Source/bhr/node_modules/.pnpm/tslib@2.6.2/node_modules/tslib/tslib.js:176:57)
    at fulfilled (/Users/zwily/Source/bhr/node_modules/.pnpm/tslib@2.6.2/node_modules/tslib/tslib.js:166:62)```

**Comment by cungminh2710** [comment]
@jasonbosco I think that's because `http` and `https` node packages aren't compatible with [Cloudflare worker](https://developers.cloudflare.com/workers/runtime-apis/nodejs/). Should be a different issue i believe

**Comment by cungminh2710** [comment]
@zwily `http` and `https` package were introduced in [v1.9.0](https://github.com/typesense/typesense-js/releases/tag/v1.9.0-0). You could use typesense v1.8.2 and install axios v1.7.2 to use Cloudflare worker - this is how I got it working. Hope that helps

**Comment by viktorlarsson** [comment]
Actually, all that is needed for it to work in edge runtimes is:

`axios.defaults.adapter = "fetch";`

I'll see if I can get it in documentation instead?

**Comment by zhihengGet** [comment]
@viktorlarsson , how do you set that tho ? seems like this lib does not expose axios

**Comment by gabrielstuff** [comment]
@zhihengGet I just tested in #95 and it works for Deno. It should work on CF.

**Comment by themerk** [comment]
For anyone struggling to get this working on Cloudflare Workers, here's my solution:

```js
import axios from 'axios';
import Typesense from 'typesense';

// Axios fetch adapter configuration for Cloudflare Workers
const fetchAdapter = await axios.getAdapter('fetch'); // Use the native fetch()
const customAxiosAdapter = (config) => fetchAdapter({ ...config, fetchOptions: { cache: 'no-store' } }); // Cloudflare doesn't support axios's default of { cache: 'default' }

new Typesense.Client({
	nodes: [ ... ],
	apiKey: 'xxxxx',
	axiosAdapter: customAxiosAdapter
});
```

Using versions:
- typesense: 3.0.6
- axios: 1.20.0

The addition of `axiosAdapter` means this issue can be closed.
