### ISSUE TITLE
Typesense-js can't parse all jsons returned by typesense

### ISSUE THREAD

**Issue by rovaniemi** [typesense/typesense-js#207]
## Description

`Typesense-js` can't parse all jsons returned by `typesense`

## Steps to reproduce

Requests the use of inflix in a collection where the inflix index does not exist.

## Expected Behavior

Typesense-js returns message ```{
	"message": "Could not find `x` in the infix index. Make sure to enable infix search by specifying `"infix": true` in the schema."
}```

## Actual Behavior

Request #1716486279846: Request to Node 0 failed due to "undefined Expected ',' or '}' after property value in JSON at position 108"

```
❗️ SyntaxError: Expected ',' or '}' after property value in JSON at position 108
    at JSON.parse (<anonymous>)
    at Object.requestOptions.transformResponse (/app/node_modules/typesense/src/Typesense/ApiCall.ts:188:40)
    at transform (/app/node_modules/typesense/node_modules/axios/lib/core/transformData.js:18:15)
    at Object.forEach (/app/node_modules/typesense/node_modules/axios/lib/utils.js:245:10)
    at Object.transformData (/app/node_modules/typesense/node_modules/axios/lib/core/transformData.js:17:9)
    at onAdapterResolution (/app/node_modules/typesense/node_modules/axios/lib/core/dispatchRequest.js:62:35)
```

## Metadata

**Typesense Version**: 26.0

**Comment by jasonbosco** [comment]
Hmmm, could you give me a JS snippet that reproduces the issue? 

Here's a template to use: https://github.com/typesense/typesense-js/blob/master/doc/examples/server/search.js

**Comment by rovaniemi** [comment]
@jasonbosco 

```
<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Typesense Browser Demo</title>
</head>
<body>
<div>
    <h1>Typesense Browser Demo</h1>
    <div>
        <input id="search-input" type="text" placeholder="search terms"/>
        <button id="search-button" type="submit" onclick=search()>Search</button>
    </div>
    <pre id="search-results">
    </pre>
</div>
<script src="../../../dist/Typesense.js"></script>
<script>
  /*
   Setup: See clientInitalization.js for quick instructions on starting the Typesense server.
  */

  // Create a client
  // We're using Typesense.Client instead of Typesense.SearchClient just for the purposes of this example, so we can index using the same client
  // You'd typically want to use Typesense.SearchClient in the browser, if you only need to perform search operations
  var typesense = new Typesense.Client({
    'nodes': [
      {
        'host': 'localhost',
        'port': '8108',
        'protocol': 'http'
      }
    ],
    'apiKey': 'xyz',
    'numRetries': 3,
    'connectionTimeoutSeconds': 10,
    'retryIntervalSeconds': 0.1,
    'healthcheckIntervalSeconds': 2,
    'logLevel': 'debug'
  })
  
    let schema = {
    'name': 'x',
    'num_documents': 0,
    'fields': [
      {
        'name': 'y',
        'type': 'string'
      }
    ]
  }


  // create a collection, in case it doesn't exist
  //    We're creating a collection from the browser just for the purposes of this example.
  //    You'd typically create a collection server-side and only use the search endpoint from the browser.
  //    So you want to pass an API key that only allows searches in the api-key field, instead of the master key when using this library in a browser.
  //    See keys.js in docs/examples/server/keys.js for an example of how to generate a search only API key.

  function search () {
    var searchTerm = document.getElementById('search-input').value
    typesense.collections('x').documents().search({
      'q': searchTerm,
      'query_by': 'y',
      'per_page': 10,
      'infix': 'always'
    }).then(function (searchResults) {
      document.getElementById('search-results').innerHTML = JSON.stringify(searchResults, null, 2)
    }).catch(function (error) {
      document.getElementById('search-results').innerHTML = error
    })
  }

</script>
</body>
</html>
```

This should repeat it. At least I managed to reproduce it locally. (However, I tested it on our environment, so I really don't know if that will be repeated in a completely empty collection.)

<img width="796" alt="image" src="https://github.com/typesense/typesense-js/assets/21308995/38cca1d3-c8f5-4917-8119-fa08a811dafc">
