### ISSUE TITLE
"Unexpected end of JSON input" error

### ISSUE THREAD

**Issue by tomika** [typesense/typesense-js#243]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `typesense@1.8.2` for the project I'm working on.

On updating typesense database I often get the following error:

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at <anonymous> (./node_modules/typesense/src/Typesense/Documents.ts:355:26)
    at Array.map (<anonymous>)
    at Documents.<anonymous> (./node_modules/typesense/src/Typesense/Documents.ts:355:10)
    at step (./node_modules/typesense/lib/Typesense/Documents.js:48:23)
    at Object.next (./node_modules/typesense/lib/Typesense/Documents.js:29:53)
    at fulfilled (./node_modules/typesense/lib/Typesense/Documents.js:20:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/typesense/src/Typesense/Documents.ts b/node_modules/typesense/src/Typesense/Documents.ts
index b4ba7b3..1679569 100644
--- a/node_modules/typesense/src/Typesense/Documents.ts
+++ b/node_modules/typesense/src/Typesense/Documents.ts
@@ -352,6 +352,7 @@ export default class Documents<T extends DocumentSchema = object>
     if (Array.isArray(documents)) {
       const resultsInJSONFormat = resultsInJSONLFormat
         .split("\n")
+        .filter((r) => r.trim() !== "")
         .map((r) => JSON.parse(r)) as ImportResponse[];
       const failedItems = resultsInJSONFormat.filter(
         (r) => r.success === false,
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

Please consider to apply this patch!
Thank you in advance, 
  Tom

**Comment by arpadgabor** [comment]
We also started facing this issue, seems like the problem actually stems from some changes on the server, because 26.0 didn't cause this for us.

**Comment by tharropoulos** [comment]
> We also started facing this issue, seems like the problem actually stems from some changes on the server, because 26.0 didn't cause this for us.

Could you provide a reproducible example that would match that case? I'll try it out with different server versions so I can find a solution that serves both cases.

**Comment by tharropoulos** [comment]
Closing this down since it hasn't seen activity in a while. Feel free to reopen if you have more information.
