### ISSUE TITLE
Error: getaddrinfo ENOTFOUND master (Mac prebuilt binary)

### ISSUE THREAD

**Issue by technoplato** [typesense/typesense-js#31]
Just trying to follow the getting started tutorial. I'm sure I'm making a terribly stupid error somewhere, but I can't figure out where.

# My Code

```js
const Typesense = require("typesense");

const searchClient = new Typesense.Client({
  masterNode: {
    host: "master",
    port: 8108,
    protocol: "http",
    apiKey: "foobar"
  }
});

let showsSchema = {
  name: "shows",
  fields: [
    { name: "name", type: "string" },
    { showName: "name", type: "string" }
  ]
};

searchClient
    .collections()
    .create(showsSchema)
    .then(console.log)
    .catch(console.log);
```

# Error
```
Error: getaddrinfo ENOTFOUND master
    at /Users/lustig/Library/Mobile Documents/com~apple~CloudDocs/Development/CLIENTS/TCT/SERVER/node_modules/typesense/lib/Typesense/Typesense/ApiCall.js:66:5
```

# TypeSense server output

![Screen Shot 2020-02-11 at 5 08 50 PM](https://user-images.githubusercontent.com/6922904/74284167-2df3c080-4cf1-11ea-827a-c6ef663d5abb.png)

```
Error: getaddrinfo ENOTFOUND master
    at /Users/lustig/Library/Mobile Documents/com~apple~CloudDocs/Development/CLIENTS/TCT/SERVER/node_modules/typesense/lib/Typesense/Typesense/ApiCall.js:66:5
```

*Please let me know if you require any more information*

**Comment by technoplato** [comment]
As I imagined, something stupid. I copied the Client initializer code verbatim.

Just needed to change the `host` to `localhost`

```js
const searchClient = new Typesense.Client({
  masterNode: {
    host: "master",
    port: 8108,
    protocol: "http",
    apiKey: "foobar"
  }
});
```
