### ISSUE TITLE
ObjectNotFound error

### ISSUE THREAD

**Issue by fluxrooms** [typesense/typesense-js#50]
getting this error when i try to create a document.
curl localhost:8108/health returns {'ok': true} but localhost:8108/ returns { "message": "Not Found"}

/Users/manav/projects/fluxroom-beta/node_modules/typesense/lib/Typesense/ApiCall.js:366
      var customErrror = new CustomErrorKlass(errorMessage);
                         ^

ObjectNotFound [Error]: Request failed with HTTP code 404 | Server said: Not Found
    at ApiCall._customErrorForResponse (/Users/manav/projects/fluxroom-beta/node_modules/typesense/lib/Typesense/ApiCall.js:366:26)
    at ApiCall._callee$ (/Users/manav/projects/fluxroom-beta/node_modules/typesense/lib/Typesense/ApiCall.js:178:70)
    at tryCatch (/Users/manav/projects/fluxroom-beta/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/manav/projects/fluxroom-beta/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/Users/manav/projects/fluxroom-beta/node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (/Users/manav/projects/fluxroom-beta/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/manav/projects/fluxroom-beta/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  httpStatus: 404
}

**Comment by jasonbosco** [comment]
@fluxrooms The root url `localhost:8108/` throwing a 404 is expected - there are no resources the server serves under `/`. Collections are available under `/collections`, etc. 

Could you post the exact JS client snippet that throws the 404? The JS client shouldn't be making calls to the root url.

**Comment by fluxrooms** [comment]
**this is my client api call**

const { Client } = require("typesense");

let typesenseClient = new Client({
  nodes: [
    {
      host: "localhost",
      port: "8108",
      protocol: "http",
    },
    // {
    //   host: "localhost",
    //   port: "7108",
    //   protocol: "http",
    // },
    // {
    //   host: "localhost",
    //   port: "9108",
    //   protocol: "http",
    // },
  ],
  apiKey: "myapikey",
  connectionTimeoutSeconds: 2,
});

module.exports = { typesenseClient };
