### ISSUE TITLE
How to use scoped search keys for search?

### ISSUE THREAD

**Issue by fekstr** [typesense/typesense-js#57]
## Description

I'm trying to use scoped search keys to limit the content that users can access. However, I don't get the key to work for search operations. What is the correct way of implementing this?

## Steps to reproduce

Create a scoped search key:

```
client
  .keys()
  .create({
    description: "Admin key",
    actions: ["documents:search"],
    collections: ["items"],
  })
  .then((key) => {
    const searchKey = client.keys().generateScopedSearchKey(key.value, {
      filter_by: `workpaceId:=1`,
      expires_at: 64723363199,
    });
    console.log(searchKey);
  })
```

Create a new client using this key as the API key:

```
const searchClient = new Typesense.Client({
  nodes: [
    {
      host: "HOSTNAME.typesense.net",
      port: "443",
      protocol: "https",
    },
  ],
  apiKey: "SCOPED_SEARCH_KEY",
  connectionTimeoutSeconds: 2,
})
```

Use the client to search among items:

```
const searchParameters = {
  q: "city",
  query_by: "tags",
  sort_by: "popularity:desc",
  filter_by: "workspaceId:=1",
};

searchClient
  .collections("items")
  .documents()
  .search(searchParameters)
  .then((searchResults) => {
    console.log(searchResults)
  })
  .catch((err) => console.error(err))
```

## Expected Behavior

Documents should be logged. I get the following when initializing the client using the admin key instead of the scoped search key:

```
{
  facet_counts: [],
  found: 1,
  hits: [
    {
      document: {
        id: '1',
        popularity: 1,
        tags: [ 'woman', 'man', 'city', 'traffic' ],
        workspaceId: '1'
      },
      highlights: [
        {
          field: 'tags',
          indices: [ 2 ],
          matched_tokens: [ [ 'city' ] ],
          snippets: [ '<mark>city</mark>' ]
        }
      ],
      text_match: 130816
    }
  ],
  out_of: 3,
  page: 1,
  request_params: { collection_name: 'items', per_page: 10, q: 'city' },
  search_time_ms: 0
}
```

## Actual Behavior

404 error:

```
ObjectNotFound [Error]: Request failed with HTTP code 404 | Server said: Not Found
    at ApiCall._customErrorForResponse (/Users/frithiofekstrom/github.com/fekstr/typesense-test/node_modules/typesense/lib/Typesense/Typesense/ApiCall.js:238:26)
    at ApiCall._callee$ (/Users/frithiofekstrom/github.com/fekstr/typesense-test/node_modules/typesense/lib/Typesense/Typesense/ApiCall.js:121:38)
    at tryCatch (/Users/frithiofekstrom/github.com/fekstr/typesense-test/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/frithiofekstrom/github.com/fekstr/typesense-test/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/Users/frithiofekstrom/github.com/fekstr/typesense-test/node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (/Users/frithiofekstrom/github.com/fekstr/typesense-test/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/frithiofekstrom/github.com/fekstr/typesense-test/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  httpStatus: 404
}
```

## Metadata

**Typesense Version**: 0.19.0

**Typesense JS version**: 0.11.2

**OS**: Typesense running on Typesense Cloud. JS running on MacOS Big Sur.

**Comment by jasonbosco** [comment]
Hi @fekstr, that is the correct way to use scoped API keys. I do see a typo in the field name that's embedded in the scoped api key: `workpace` instead of `workspace`:

```js
const searchKey = client.keys().generateScopedSearchKey(key.value, {
      filter_by: `workpaceId:=1`,
      expires_at: 64723363199,
    });
```

Could you check if fixing that solves the issue?

**Comment by fekstr** [comment]
Well, that was simple. Thanks a lot @jasonbosco! It would be nice, if possible, to get an error message saying that the field does not exist.

**Comment by jasonbosco** [comment]
Yup, I've made a note to improve error messaging in this scenario. We do return the exact field name in the error message when unknown fields are used outside of scoped search key, so need to account for this use case as well.
