### ISSUE TITLE
Error for missing header is sent when passing a bad API key

### ISSUE THREAD

**Issue by Scalahansolo** [typesense/typesense-js#70]
## Description

When using the API as described by the docs, I am getting the a missing heading error

## Steps to reproduce

```
const getTypeSenseClient = () => {
  
  const secret: { readKey; adminKey; host } = typeSenseSecret()
  return new Client({
    'nodes': [{
      'host': secret.host,
      'port': '443',
      'protocol': 'https'
    }],
    'apiKey': secret.adminKey,
    'connectionTimeoutSeconds': 2
  })
}

const importMessages = async () => {
  await connectDB(false, false)
  
  const messageRepo = getRepository(Message)
  const typesenseClient = getTypeSenseClient()
  
  const fetchedMessages = await messageRepo.find({
    select: ["timestamp", "type", "content", "senderId", "id", "chatId", "deleted"],
    where: {type: "draft"}
  })
  
  const parsedMessages = fetchedMessages.filter((msg) => {
    return JSON.parse(msg.content) !== null
  }).map( (msg) => {
    const messageContent = JSON.parse(msg.content).blocks.reduce((acc, current) => {
      return acc + current.text + "\n"
    }, "")
    
    return {
      content: messageContent,
      timestamp: new Date(msg.timestamp).getTime(),
      senderId: msg.senderId,
      type: msg.type,
      upload: 'false',
      chatId: msg.chatId,
      id: msg.id,
      deleted: msg.deleted
    }
  })
  
  typesenseClient.collections('messages').documents().import(parsedMessages, {action: 'create'})
}
```

Results in the following error 
```
/Users/sean/workspace/pesto-repos/pesto/infra-2/node_modules/typesense/lib/Typesense/Typesense/ApiCall.js:261
    const customErrror = new CustomErrorKlass(errorMessage)
                         ^
RequestUnauthorized [Error]: Request failed with HTTP code 401 | Server said: Forbidden - a valid `x-typesense-api-key` header must be sent.
    at ApiCall._customErrorForResponse (/Users/sean/workspace/pesto-repos/pesto/infra-2/node_modules/typesense/lib/Typesense/Typesense/ApiCall.js:261:26)
    at ApiCall._callee$ (/Users/sean/workspace/pesto-repos/pesto/infra-2/node_modules/typesense/lib/Typesense/Typesense/ApiCall.js:137:38)
    at tryCatch (/Users/sean/workspace/pesto-repos/pesto/infra-2/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/Users/sean/workspace/pesto-repos/pesto/infra-2/node_modules/regenerator-runtime/runtime.js:294:22)
    at Generator.next (/Users/sean/workspace/pesto-repos/pesto/infra-2/node_modules/regenerator-runtime/runtime.js:119:21)
    at asyncGeneratorStep (/Users/sean/workspace/pesto-repos/pesto/infra-2/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/Users/sean/workspace/pesto-repos/pesto/infra-2/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  httpStatus: 401
}
```

**Typsense Version**:  0.15.0

**OS**: mac

**Comment by jasonbosco** [comment]
@Scalahansolo Could you also post the contents of `typeSenseSecret()` (minus the actual api keys)

**Comment by Scalahansolo** [comment]
@jasonbosco per our email chain, I had my read key and admin key mixed up :(. Again, as mentioned in that thread, I think it would be good to update the message on a bad key to be more clear about the issue as opposed to just saying the header wasn't included.

**Comment by jasonbosco** [comment]
Phew! Glad it wasn't a deeper issue :)

The reason the error message is vague is because from a security perspective, we don't want to provide information about a key not existing vs it existing & not having the right permissions, for a potential malicious actor to use as a source of information.

**Comment by Scalahansolo** [comment]
@jasonbosco I definitely understand the vagueness from a security perspective. With that being said however, even a malicious user would be able to tell "I've definitely included that header". Something along the lines of "401 Unauthorized: Invalid API Key" would be much better.
